# Generated by Django 4.0.4 on 2022-05-31 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0003_tag_post_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISH', 'Publish'), ('ARCHIVE', 'Archive')], default='DRAFT', max_length=64),
        ),
    ]
